name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Mono:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Mono
        run: |
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update
          sudo apt install mono-devel
      
      - name: run mc-compiled.exe
        run: mono mc-compiled-linux/mc-compiled.exe --regolith